refractor

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -251,20 +251,27 @@ install:
       fi
 
 script:
+          # ${lib_bash_banner} "running setup.py test";
+          # ${CMDPREFIX} ${python_command} ./setup.py test;
+          #     if [[ $? -eq 0 ]]; then
+          #         ${lib_bash_banner} "setup.py test - OK";
+          #     else
+          #         ${lib_bash_banner_warning} "setup.py test - FAILED";
+          #         exit 1;
+          #     fi
+
     - if [[ -f ./setup.py ]]; then
           ${lib_bash_banner} "Installing Pytest requirements";
           ${CMDPREFIX} ${pip_command} install -r ./requirements_pytest.txt;
           ${CMDPREFIX} ${pip_command} install codecov;
           ${CMDPREFIX} ${pip_command} install pytest-cov;
 
-          ${lib_bash_banner} "running setup.py test";
-          ${CMDPREFIX} ${python_command} ./setup.py test;
-              if [[ $? -eq 0 ]]; then
-                  ${lib_bash_banner} "setup.py test - OK";
-              else
-                  ${lib_bash_banner_warning} "setup.py test - FAILED";
-                  exit 1;
-              fi
+
+
+
+
+
+
 
           ${lib_bash_banner} "running pip install --upgrade";
           ${CMDPREFIX} ${pip_command} install ${github_master} --upgrade;
